AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Infrastructure for dbowland.com links project

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - test
    Description: Environment for deploy

Mappings:
  EnvironmentMap:
    prod:
      project: links
    test:
      project: links-test

Resources:
  # Analytics

  Pinpoint:
    Type: AWS::Pinpoint::App
    Properties:
      Name: !FindInMap [EnvironmentMap, !Ref Environment, project]
      Tags:
        'created-by': 'links-infrastructure'
        'created-for': 'links'

Outputs:
  PinpointId:
    Description: Application ID for Pinpoint analytics
    Value: !Ref Pinpoint
