AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Infrastructure for dbowland.com links project

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - test
    Description: Environment for deploy

Mappings:
  EnvironmentMap:
    prod:
      lambdaBucketName: links-lambda
      project: links
      roleNameCloudFormation: links-cloudformation
      roleNamePipeline: links-pipeline
    test:
      lambdaBucketName: links-lambda-test
      project: links-test
      roleNameCloudFormation: links-cloudformation-test
      roleNamePipeline: links-pipeline-test

Resources:
  # Deployment storage

  LambdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: false
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !FindInMap [EnvironmentMap, !Ref Environment, lambdaBucketName]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: 'created-by'
          Value: 'links-infrastructure'
        - Key: 'created-for'
          Value: 'links'

  # Deployment roles

  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub
            - '${Project}-cloudformation'
            - Project: !FindInMap [EnvironmentMap, !Ref Environment, project]
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                NotAction:
                  - 'iam:*User'
                  - 'organizations:*'
                  - 'account:*'
                Resource: '*'
      RoleName: !FindInMap [EnvironmentMap, !Ref Environment, roleNameCloudFormation]

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub '${AWS::AccountId}'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub
            - '${Project}-pipeline'
            - Project: !FindInMap [EnvironmentMap, !Ref Environment, project]
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'iam:PassRole'
                Resource: !Sub '${CloudFormationRole.Arn}'
              - Effect: Allow
                Action: 'cloudformation:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:DeleteObject'
                  - 's3:GetObject*'
                  - 's3:PutObject*'
                  - 's3:GetBucket*'
                  - 's3:List*'
                Resource:
                  - 'arn:aws:s3:::links-ui-source/*'
                  - 'arn:aws:s3:::links-ui-source'
                  - 'arn:aws:s3:::links-ui-test/*'
                  - 'arn:aws:s3:::links-ui-test'
                  - !Sub 'arn:aws:s3:::${LambdaBucket}/*'
                  - !Sub 'arn:aws:s3:::${LambdaBucket}'
      RoleName: !FindInMap [EnvironmentMap, !Ref Environment, roleNamePipeline]

  # Deployment users

  LinksApiUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: !Sub
            - '${Project}-pipeline'
            - Project: !FindInMap [EnvironmentMap, !Ref Environment, project]
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'sts:AssumeRole'
                Resource:
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/links-pipeline'
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/links-pipeline-test'
      Tags:
        - Key: 'created-by'
          Value: 'links-infrastructure'
        - Key: 'created-for'
          Value: 'links'

  UiUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: !Sub
            - '${Project}-pipeline'
            - Project: !FindInMap [EnvironmentMap, !Ref Environment, project]
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'sts:AssumeRole'
                Resource:
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/links-pipeline'
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/links-pipeline-test'
      Tags:
        - Key: 'created-by'
          Value: 'links-infrastructure'
        - Key: 'created-for'
          Value: 'links'
